### ISSUE TITLE
Catch and handle API errors

### ISSUE THREAD

**Issue by rokoucha** [otofune/mozuku#11]
デカすぎるPOSTすると破滅する

**Comment by otofune** [comment]
どういう風になる？

**Comment by rokoucha** [comment]
500になってtextareaがdisabledのまま
![image](https://user-images.githubusercontent.com/6058487/57063774-4913b780-6cff-11e9-8fd3-b2fd8b5a7504.png)

**Comment by otofune** [comment]
naruhodone
