### ISSUE TITLE
textareaを目立たせてほしい

### ISSUE THREAD

**Issue by rokoucha** [otofune/mozuku#12]
どこまでがtextareaか分からない

**Comment by otofune** [comment]
これ、投稿欄とボタンを分離するやつで同時に対処できそうなやつかな

**Comment by rokoucha** [comment]
色変わったし分かりやすくなったし閉じても良いと思いますが皆さんはいかが？ @otofune @p-chan

**Comment by p-chan** [comment]
現状で快適に使えてるし、閉じて良いと思う

**Comment by otofune** [comment]
気づいてなかった、よさそう
