### ISSUE TITLE
どこかにseaへの動線があると便利そう

### ISSUE THREAD

**Issue by rokoucha** [otofune/mozuku#14]
アカウント設定とかはseaにあるので、飛べると嬉しい!
左上のユーザー名クリックのメニューとかに置くと良いかも

**Comment by rinsuki** [comment]
seaにはoauthまわりと招待機能しかおかない予定なのであんまりいらなさそう

**Comment by rokoucha** [comment]
ログアウト周りがダルいのであるとそこそこ嬉しいと思った

**Comment by otofune** [comment]
マルチ・アカウント太郎？

**Comment by rokoucha** [comment]
いらねえんだわ
