### ISSUE TITLE
Auto-styling generated css.d.ts files

### ISSUE THREAD

**Issue by otofune** [otofune/mozuku#150]

**Comment by p-chan** [comment]
最悪 `yarn gen-csstype && yarn format` とかいうのがある

**Comment by otofune** [comment]
わかる、そのときに css.d.ts だけ指定したら問題ないよなーと思ってるから解決自体はサクッとできそう

**Comment by otofune** [comment]
https://github.com/otofune/mozuku/commit/1e5062696be844f4c31717f202e96d0aa7f34ed6
