### ISSUE TITLE
Scroll value changes when focus on postForm

### ISSUE THREAD

**Issue by p-chan** [otofune/mozuku#156]
ガクってなって、鬱になっちゃう

![Jun-24-2019 18-35-39](https://user-images.githubusercontent.com/7752475/60008671-6df92b00-96af-11e9-94b3-ec4ee4375fab.gif)

**Comment by p-chan** [comment]
あと iOS 13 beta 2 で正常に動作しないとの報告がある

**Comment by rokoucha** [comment]
Firefox for Android 67.0.3(Android 9)だとタッチしてフォーカス当てるとキーボードが出てきて上にずれるので最終的にスクロールがなかったことになってしまい最悪

**Comment by rinsuki** [comment]
> アドミン太郎 @.admin
> フォーカスするやつ、position: sticky;top: 0;とかでもいい気がする

**Comment by rokoucha** [comment]
![piyo](https://user-images.githubusercontent.com/6058487/60010625-1ceb3600-96b3-11e9-9bd2-d6eafeccc6ce.gif)
フォーカス当たってる状態スクロールを動かしてから投稿ボタン押すとスクロールするだけなのもつらい

**Comment by otofune** [comment]
sticky にしちゃった。デザインとか崩壊の説があるのであとでよしなにしたい (特に PC で)
