### ISSUE TITLE
投稿添付画像の四隅ラウンドさせる

### ISSUE THREAD

**Issue by otofune** [otofune/mozuku#163]
やるだけ
アイコンとかアップロード画面と差異がある

**Comment by p-chan** [comment]
画像のラウンド数を css vars で決めちゃってもイイかもね

**Comment by otofune** [comment]
@p-chan お！たしかに。やります
あるいは img にルートで round つけちゃう？それは微妙か

**Comment by p-chan** [comment]
@otofune ルートでimgに付けるのは微妙かな
css、global にアレコレしていくと地獄になりがちなので、面倒臭さはあるけど、できるだけスコープはせまくしたい

**Comment by otofune** [comment]
https://github.com/otofune/mozuku/commit/a676ea0161a6ea52794d27e03e62b14e9599f8ef
