### ISSUE TITLE
めちゃくちゃ長いテキストを入れるとTLが消滅する

### ISSUE THREAD

**Issue by rinsuki** [otofune/mozuku#195]
![image](https://user-images.githubusercontent.com/6533808/62267098-f4025180-b465-11e9-8b88-a56cc3dbd958.png)
伸びる上限が欲しい

**Comment by otofune** [comment]
終わった

**Comment by otofune** [comment]
終わった

**Comment by otofune** [comment]
まぁ文字制限までしか伸びないのが妥当っぽいよな

**Comment by otofune** [comment]
https://github.com/andreypopp/react-textarea-autosize#props 伸びないようにできそう styleあてる方向で

**Comment by otofune** [comment]
これ永遠に忘れてたので直します
