### ISSUE TITLE
Introduce automatically testing on Circle CI

### ISSUE THREAD

**Issue by otofune** [otofune/mozuku#20]
- いま手動でデプロイしているがめんどくさいのでやめたい
- prettier かけ忘れてたら自動で直すか怒って欲しい
- テスト書いたら動いて欲しい

**Comment by rinsuki** [comment]
netlify にすれば自動でビルドとデプロイやってくれそう

**Comment by otofune** [comment]
そうかも

**Comment by otofune** [comment]
netlify 使ったことないしねっとりするのありだな

**Comment by otofune** [comment]
テストしたい文脈と CD したい文脈があって、CD したい文脈の方が熱いのでそっち別にきるか

**Comment by otofune** [comment]
- Deploy with Netlify #21
- とりあえず prettier 動かした Azure Pipelines 導入 #39
