### ISSUE TITLE
Error on console with Assertion failed when pushed Enter key in textarea

### ISSUE THREAD

**Issue by rokoucha** [otofune/mozuku#30]
```Assertion failed: Input argument is not an HTMLInputElement```

**Comment by otofune** [comment]
もう少し条件を教えてほしいです

**Comment by rokoucha** [comment]
本当にtextareaでEnterキーを押すだけです

| name | version |
|----------|------------|
| Firefox | 67.0b15 64bit Arch Linux |

**Comment by otofune** [comment]
私の環境でも textarea で入力しているだけで type: not-match-pattern 出たので何か関連しているかもしれない

**Comment by otofune** [comment]
↑ping に対応してなかっただけぽい

**Comment by otofune** [comment]
再現しないので一度クローズします
@atnanasi また起きたらスタックトレースとともに教えてください！

**Comment by rokoucha** [comment]
https://github.com/mui-org/material-ui/issues/14860 俺が悪かった(LastPassが悪い)
