### ISSUE TITLE
Use ws instead of native WebSocket

### ISSUE THREAD

**Issue by otofune** [otofune/mozuku#35]
再接続はうまくかけないし ping/pong フレームは送れないしで、サーバー側は ws なのでそっちに寄せちゃおうってやつです

**Comment by rinsuki** [comment]
ws は Node.js で使うものでブラウザ上では使えないのでは…

**Comment by otofune** [comment]
ほんまや悲しい、サーバーから ping 来るようになったなら問題なさそう

**Comment by otofune** [comment]
ほんまや悲しい、サーバーから ping 来るようになったなら問題なさそう
