### ISSUE TITLE
Show OGP of links in posts

### ISSUE THREAD

**Issue by otofune** [otofune/mozuku#41]

**Comment by p-chan** [comment]
@otofune ロゴを使った素材が必要であれば作るので、言ってください

**Comment by otofune** [comment]
@p-chan :pray: 
ただクライアントとして OGP を出すのではなく投稿内のリンクの OGP を拾ってきて表示する方を意識してたので必要なさそうな気はする :bow:

**Comment by otofune** [comment]
あーでもそうか、OGP にクロールされたときの表示をきれいにするのもいいな、やりたいかも

**Comment by rinsuki** [comment]
招待制でそこやるの、うーん感がある

**Comment by otofune** [comment]
やるとしていまタイトルしか出ないのでロゴ出すくらいなので別にいいのでは？感はある

**Comment by otofune** [comment]
#48 作ったのでそこで設定有効にすると ON になるみたいな感じにするか
