### ISSUE TITLE
リプライ先表示

### ISSUE THREAD

**Issue by rokoucha** [otofune/mozuku#613]
> 137155 ：すっす ：2020/07/14(火) 06:10:20.763 ID: dolphin
    投稿欄の上にニュっと出ると投稿時は良さそう〜というのは思っている（その場合は replyToPostId のリレーは必要ないし）

> 137156 ：すっす ：2020/07/14(火) 06:10:24.015 ID: dolphin
    ある

>  137157 ：!omikuji → ★大吉 ：2020/07/14(火) 06:10:56.670 ID: a
    ニュルッと1remぐらいで出るのがまあ理想っぽそう

> 137158 ：!omikuji → ★大吉 ：2020/07/14(火) 06:11:09.867 ID: a
    実装してみんことにはよくわからんけど

> 137159 ：すっす ：2020/07/14(火) 06:11:34.869 ID: dolphin
    @{screenname} 本文 … がどのくらいマトモにスマホで見れるかわからん問題

-----------

> 137168 ：Fidei defensatrix✔️ ：2020/07/14(火) 06:19:04.572 ID: abcdefgh
    リプライ番号のとこをマウスオーバーで該当メッセージが出てくるといいきがする

> 137169 ：Fidei defensatrix✔️ ：2020/07/14(火) 06:19:08.167 ID: abcdefgh
    5ch のパクり

> 137170 ：Fidei defensatrix✔️ ：2020/07/14(火) 06:19:47.959 ID: abcdefgh
    こういう感じで
> ![image](https://user-images.githubusercontent.com/6058487/87387057-e1344e80-c5dc-11ea-9876-e09b1fd4c01d.png)

> 137172 ：すっす ：2020/07/14(火) 06:20:22.793 ID: dolphin
    スマホでどうすんねん

> 137173 ：すっす ：2020/07/14(火) 06:20:29.955 ID: dolphin
    PC としてはありっぽい

> 137174 ：Fidei defensatrix✔️ ：2020/07/14(火) 06:24:28.652 ID: abcdefgh
    タッチでモーダルとして表示?

> 137175 ：Fidei defensatrix✔️ ：2020/07/14(火) 06:24:54.382 ID: abcdefgh
    別にクリックでもモーダルとして表示して良い気がする

> 137176 ：すっす ：2020/07/14(火) 06:26:20.279 ID: dolphin
    たし :crab:

**Comment by rokoucha** [comment]
5ch だとクリックすると _blank でリンク先投稿が開かれた

**Comment by otofune** [comment]
#437 と被ってた
