### ISSUE TITLE
リプライの投稿時、投稿フォームからリプライ先の簡易ビューおよび削除がしたい

### ISSUE THREAD

**Issue by otofune** [otofune/mozuku#633]
要求
---
- リプライ先を間違えていることに気付きにくいので、わかりやすくしたい
- (タイムライン上に投稿欄の機能が漏れているのを直したい)
  + 選択は仕方ないので、それ意外
  + 例) `…` という表示によって選択中のリプライを表示すること

どうする
---
- 投稿欄の上部に投稿先を表示し、リプライ解除もそこからできるようにしたい

**Comment by rokoucha** [comment]
#695 で解決してそう

**Comment by otofune** [comment]
できてそう
