### ISSUE TITLE
URL 末尾に ZWSP が混入することがあるので除去する

### ISSUE THREAD

**Issue by otofune** [otofune/mozuku#634]
なに
--
- iOS で ZWSP が混入することがある？
- 例) Twitter の共有から URL コピペして貼る時に発生
  + Twitter for iOS の投稿欄からコピー
- U+200B が入ってジャンプできずに迷惑なので、これを消す
  + パーセントエンコードなら %E2%80%AC

どこで
--
- [x] 投稿時に除去
- [x] 表示制御
  + あったほうがいいが……

**Comment by rinsuki** [comment]
というかそもそも bottlemail でエスケープなし ZWSP をリンクにしないべきなのでは

**Comment by otofune** [comment]
ちゃんと URL の許容文字を定義すべきというのはわかるんだけど、どういうフォーマットで投稿されてるかわからないので日本語とかを落とせなくて仕様に乗れなくて泣いちゃうんだよね

**Comment by otofune** [comment]
ZWSP だけ除外するコード書いてもいいけど

**Comment by rinsuki** [comment]
とりあえず ZWSP 除外だけでいいと思うけど

**Comment by otofune** [comment]
そっちの方が全体最適ではありそうだしそうすっかあ……と思ったけどパーセントエンコードを解決してないので decode しなきゃいけないのか（失敗することがあるので全部ライブラリ外に押し付けている）
ZWSP 直 or %E2%80%AC をハンドリングしなきゃいけないのちょっと苦しい

**Comment by otofune** [comment]
多段構成で post process で消せば解決だわ、これでいきます

**Comment by otofune** [comment]
投稿時の除去はしたいが、どう実現するかという問題があるなー

**Comment by otofune** [comment]
bottlemail の node.value を合成する関数作ればいいか
